ProjectVFront/Controllers/AuthController.cs
using AutoMapper;
using Flurl.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectVFront.Application.Services;
using ProjectVFront.Crosscutting.Dtos;
using ProjectVFront.Crosscutting.Utils;
using ProjectVFront.WebClient.ViewModels;
using System.Diagnostics;

namespace ProjectVFront.Controllers
{
    public class AuthController : Controller
    {
        private readonly ILogger<AuthController> _logger;
        private readonly IUserManagementService _userManagement;
        private readonly IMapper _mapper;

        public AuthController(ILogger<AuthController> logger, IUserManagementService userManagement, IMapper mapper)
        {
            _logger = logger;
            _userManagement = userManagement;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return Login();
        }

        [HttpGet]
        [Route("{action}")]
        [AllowAnonymous]
        public IActionResult Login()
        {
            if (User != null && User.Identity != null && User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Summary");

            return View();
        }


        [HttpPost]
        [Route("{action}")]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LogInViewModel request)
        {
            try
            {
                var dto = _mapper.Map<LogInRequestDto>(request);

                var tokenResponse = await _userManagement.LoginAsync(dto);

                var cookieOptions = new CookieOptions { HttpOnly = true, SameSite = SameSiteMode.Strict };

                Response.Cookies.Append(HttpConstants.XAccessToken, tokenResponse, cookieOptions);

                return RedirectToAction("Index", "Summary");
            }
            catch (FlurlHttpException ex)
            {
                ViewBag.Error = await GetErrorMessageAsync(ex);
            }

            return View();
        }

        [HttpGet]
        [Route("{action}")]
        [AllowAnonymous]
        public IActionResult SignUp()
        {
            if (User != null && User.Identity != null && User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Summary");

            return View();
        }


        [HttpPost]
        [Route("{action}")]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(SignUpViewModel request)
        {
            try
            {
                var dto = _mapper.Map<SignUpRequestDto>(request);
                await _userManagement.SignUpAsync(dto);

                return RedirectToAction("Login");
            }
            catch (FlurlHttpException ex)
            {
                ViewBag.Error = await GetErrorMessageAsync(ex);
            }

            return View();
        }

        [HttpGet]
        [Route("{action}")]
        [Authorize]
        public IActionResult Logout()
        {
            Response.Cookies.Append(HttpConstants.XAccessToken, string.Empty);

            return RedirectToAction("Login");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private async Task<string> GetErrorMessageAsync(FlurlHttpException ex)
        {
            if (ex.StatusCode == 400)
            {
                var httpError = await ex.GetResponseJsonAsync<HttpError>();
                return httpError.Message;
            }

            throw ex;
        }
    }
}

ProjectVFront/Controllers/CategoriesController.cs
using Flurl.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectVFront.Application.Services;
using ProjectVFront.Crosscutting.Dtos;
using ProjectVFront.WebClient.ViewModels;
using System.Diagnostics;

namespace ProjectVFront.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ILogger<CategoriesController> _logger;
        private readonly ICategoryService _categoryService;

        public CategoriesController(ILogger<CategoriesController> logger, ICategoryService categoryService)
        {
            _logger = logger;
            _categoryService = categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var categoryListDto = await _categoryService.GetAllCategoriesAsync();
            var viewmodel = new CategoriesViewModel() { Categories = categoryListDto };

            ModelState.Clear();

            return View(viewmodel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CategoriesViewModel viewmodel)
        {
            try
            {
                await _categoryService.CreateCategoryAsync(viewmodel.AddCategoryRequestDto);
            }
            catch (FlurlHttpException ex)
            {
                _logger.LogError(ex.Message);
                TempData["Error"] = await GetErrorMessageAsync(ex);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                throw ex;
            }

            return RedirectToAction("index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoriesViewModel viewmodel)
        {
            await _categoryService.EditCategoryAsync(viewmodel.EditCategoryRequestDto);

            return RedirectToAction("index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private async Task<string> GetErrorMessageAsync(FlurlHttpException ex)
        {
            if (ex.StatusCode == 400)
            {
                var httpError = await ex.GetResponseJsonAsync<HttpError>();
                return httpError.Message;
            }

            throw ex;
        }
    }
}

ProjectVFront/Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectVFront.Application.Services;
using ProjectVFront.Crosscutting.Dtos;
using ProjectVFront.WebClient.ViewModels;
using System.Diagnostics;

namespace ProjectVFront.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ILogger<TransactionsController> _logger;
        private readonly ITransactionService _transactionService;
        private readonly IFormatProvider _formatProvider;

        public TransactionsController(
            ILogger<TransactionsController> logger,
            ITransactionService transactionService,
            IFormatProvider formatProvider)
        {
            _logger = logger;
            _transactionService = transactionService;
            _formatProvider = formatProvider;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] int? year, int? month)
        {
            var viewmodel = new TransactionsViewModel(_formatProvider);

            try
            {
                var now = DateTime.Now;
                var from = new DateTime(year ?? now.Year, month ?? now.Month, 1);
                var lastDayOfMonth = from.AddMonths(1).AddDays(-1);
                var to = new DateTime(lastDayOfMonth.Year, lastDayOfMonth.Month, lastDayOfMonth.Day, 23, 59, 59);

                var beforeMonth = from.AddMonths(-1);
                var afterMonth = from.AddMonths(1);

                ViewBag.BeforeMonth = beforeMonth.Month;
                ViewBag.BeforeYear = beforeMonth.Year;

                ViewBag.AfterMonth = afterMonth.Month;
                ViewBag.AfterYear = afterMonth.Year;

                ViewBag.Year = from.ToString("yyyy", _formatProvider);
                ViewBag.Month = from.ToString("MMMM", _formatProvider);
                
                var transactionsRequest = new GetTransactionsRequestDto(from, to, null);
                var transactionsListDto = await _transactionService.GetAllTransactionsWithCategoryInfo(transactionsRequest);
                viewmodel.Transactions = transactionsListDto;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }

            ModelState.Clear();

            return View(viewmodel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectVFront/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - I Get Money</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectVFront.styles.css" asp-append-version="true" />
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectVFront</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
@*    <div class="container">
*@       @* <main role="main" class="pb-3">*@
            @RenderBody()
     @*   </main>*@
@*    </div>
*@
   @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjectVFront - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectVFront/Views/Shared/_LayoutLogged.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - I Get Money</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectVFront.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand mr-1" asp-area="" asp-controller="Summary" asp-action="Index">
                    <img src="/img/logo.png" alt="logo" width="30" height="30" class="d-inline-block align-text-top mr-1">
                    I Get Money
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Summary" asp-action="Index">Summary</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item d-block d-md-none">
                            <a class="nav-link text-dark" asp-area="" asp-controller="user" asp-action="edit">Edit user profile</a>
                        </li>
                        <li class="nav-item d-block d-md-none">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
                <div class="d-none d-md-flex">
                    <span class="fs-5">Hello @User?.Identity?.Name</span>
                    <div class="dropdown">
                        <a class="dropdown-toggle d-flex align-items-center ms-1" href="#" id="navbarDropdownMenuAvatar" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="/img/user.png" alt="user" width="30" class="roudend-circle ms-1" loading="lazy">
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end mt-3" aria-labelledby="navbarDropdownMenuAvatar">
                            <li><a class="dropdown-item" asp-controller="user" asp-action="edit">Edit user profile</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <footer class="border-top footer text-muted position-fixed bottom-0 py-1 footer-light bg-white d-flex">
        <div class="container-fluid lh-sm d-flex justify-content-between">
            <small>&copy; 2022 - I Get Money</small>
            <small>v @typeof(Program).Assembly.GetName().Version</small>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>